name: Multi Job CI

on:
  push:
    branches: [ "main" ]

jobs:s

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t revision-app .

  test:
    runs-on: ubuntu-latest
    needs: build   # ğŸ‘ˆ this makes test wait for build

    steps:
      - uses: actions/checkout@v4

      - name: Run container
        run: docker run revision-app

  deploy:
    runs-on: ubuntu-latest
    needs: test   # ğŸ‘ˆ deploy waits for test

    steps:
      - name: Fake deploy
        run: echo "Deploying application ğŸš€"
